#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xapian-core
Version  : 1.4.5
Release  : 1
URL      : https://oligarchy.co.uk/xapian/1.4.5/xapian-core-1.4.5.tar.xz
Source0  : https://oligarchy.co.uk/xapian/1.4.5/xapian-core-1.4.5.tar.xz
Summary  : The Xapian Probabilistic Information Retrieval Library
Group    : Development/Tools
License  : GPL-2.0
Requires: xapian-core-bin
Requires: xapian-core-lib
Requires: xapian-core-doc
Requires: xapian-core-data
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(zlib)
BuildRequires : valgrind

%description
Xapian is an Open Source Probabilistic Information Retrieval Library. It
offers a highly adaptable toolkit that allows developers to easily add advanced
indexing and search facilities to applications.

%package bin
Summary: bin components for the xapian-core package.
Group: Binaries
Requires: xapian-core-data

%description bin
bin components for the xapian-core package.


%package data
Summary: data components for the xapian-core package.
Group: Data

%description data
data components for the xapian-core package.


%package dev
Summary: dev components for the xapian-core package.
Group: Development
Requires: xapian-core-lib
Requires: xapian-core-bin
Requires: xapian-core-data
Provides: xapian-core-devel

%description dev
dev components for the xapian-core package.


%package doc
Summary: doc components for the xapian-core package.
Group: Documentation

%description doc
doc components for the xapian-core package.


%package lib
Summary: lib components for the xapian-core package.
Group: Libraries
Requires: xapian-core-data

%description lib
lib components for the xapian-core package.


%prep
%setup -q -n xapian-core-1.4.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1511311568
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1511311568
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/cmake/xapian/xapian-config-version.cmake
/usr/lib64/cmake/xapian/xapian-config.cmake

%files bin
%defattr(-,root,root,-)
/usr/bin/copydatabase
/usr/bin/quest
/usr/bin/simpleexpand
/usr/bin/simpleindex
/usr/bin/simplesearch
/usr/bin/xapian-check
/usr/bin/xapian-compact
/usr/bin/xapian-config
/usr/bin/xapian-delve
/usr/bin/xapian-metadata
/usr/bin/xapian-progsrv
/usr/bin/xapian-replicate
/usr/bin/xapian-replicate-server
/usr/bin/xapian-tcpsrv

%files data
%defattr(-,root,root,-)
/usr/share/xapian-core/stopwords/arabic.list
/usr/share/xapian-core/stopwords/danish.list
/usr/share/xapian-core/stopwords/dutch.list
/usr/share/xapian-core/stopwords/english.list
/usr/share/xapian-core/stopwords/finnish.list
/usr/share/xapian-core/stopwords/french.list
/usr/share/xapian-core/stopwords/german.list
/usr/share/xapian-core/stopwords/hungarian.list
/usr/share/xapian-core/stopwords/italian.list
/usr/share/xapian-core/stopwords/norwegian.list
/usr/share/xapian-core/stopwords/portuguese.list
/usr/share/xapian-core/stopwords/russian.list
/usr/share/xapian-core/stopwords/spanish.list
/usr/share/xapian-core/stopwords/swedish.list

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/xapian/attributes.h
/usr/include/xapian/compactor.h
/usr/include/xapian/constants.h
/usr/include/xapian/constinfo.h
/usr/include/xapian/database.h
/usr/include/xapian/dbfactory.h
/usr/include/xapian/deprecated.h
/usr/include/xapian/derefwrapper.h
/usr/include/xapian/document.h
/usr/include/xapian/enquire.h
/usr/include/xapian/error.h
/usr/include/xapian/errorhandler.h
/usr/include/xapian/eset.h
/usr/include/xapian/expanddecider.h
/usr/include/xapian/geospatial.h
/usr/include/xapian/intrusive_ptr.h
/usr/include/xapian/iterator.h
/usr/include/xapian/keymaker.h
/usr/include/xapian/matchspy.h
/usr/include/xapian/mset.h
/usr/include/xapian/positioniterator.h
/usr/include/xapian/postingiterator.h
/usr/include/xapian/postingsource.h
/usr/include/xapian/query.h
/usr/include/xapian/queryparser.h
/usr/include/xapian/registry.h
/usr/include/xapian/stem.h
/usr/include/xapian/termgenerator.h
/usr/include/xapian/termiterator.h
/usr/include/xapian/types.h
/usr/include/xapian/unicode.h
/usr/include/xapian/valueiterator.h
/usr/include/xapian/valuesetmatchdecider.h
/usr/include/xapian/version.h
/usr/include/xapian/visibility.h
/usr/include/xapian/weight.h
/usr/lib64/libxapian.so
/usr/lib64/pkgconfig/xapian-core.pc
/usr/share/aclocal/*.m4

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/xapian\-core/*
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxapian.so.30
/usr/lib64/libxapian.so.30.4.0
